name: Preview Contentful Deploy

on:
  push: 
    branches: [ main ]
    
  repository_dispatch:
    types: [ contentful.publish ]

jobs:
  build-preview:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with: 
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2.3.1
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 14
        cache: yarn
    
    - name: Install Dependencies & Build Website
      env:
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        PATH_PREFIX: /inclusive-hindi/
      run: |
        yarn
        yarn build
    
    - name: Deploy 🚀
      uses: crazy-max/ghaction-github-pages@v2.5.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        build_dir: public
        jekyll: false

